import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// using a different layout for different app routes:  https://stackoverflow.com/questions/77806627/how-to-use-a-completely-different-layout-in-a-nested-component-in-nextjs-app-rou
// using route groups:  https://nextjs.org/docs/app/api-reference/file-conventions/route-groups
export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>){
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
};
