import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { defineQuery } from "next-sanity";
// import { sanityFetch } from "@/sanity/lib/live";
// import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
// ---------- Sanity ----------
import { SanityLive } from "@/sanity/lib/live";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// sanity query to make navbar
// const NAVBAR_QUERY = defineQuery(`{'slugs': *[pageType == 'page']}`);


// using a different layout for different app routes:  https://stackoverflow.com/questions/77806627/how-to-use-a-completely-different-layout-in-a-nested-component-in-nextjs-app-rou
// using route groups:  https://nextjs.org/docs/app/api-reference/file-conventions/route-groups
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // query sanity and get link data
  // const { data } = await sanityFetch({query: NAVBAR_QUERY});
  // console.log("in the layout", data.slugs)

  // const allLinks = data.slugs.map(slug => {
  //   // console.log(slug)
  //   return {
  //     pageTitle: slug.page_title,
  //     link: slug.slug.current
  //   };
  // });

  // create an array with just he slugs
  // console.log(allLinks)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar links={allLinks} /> */}
        {children}

        {/* ---------- Sanity ---------- */}
        {/* <SanityLive /> */}

        {/* <Footer /> */}
      </body>
    </html>
  );
}
